Remove validations so it will work in gitlab

diff --git a/deploy-git-hook b/deploy-git-hook
--- a/deploy-git-hook
+++ b/deploy-git-hook
@@ -80,23 +80,23 @@ if [ -z "${GIT_REPO}" ]; then
 fi
 
 # Check if the repo specified is a submodule
-if [ -f "${GIT_REPO}/.git" ]; then
-  SUBMODULE_REPO=$(cat "${GIT_REPO}/.git" | grep 'gitdir' | awk '{print $2}')
-  GIT_REPO="$(cd "${GIT_REPO}" ; cd "${SUBMODULE_REPO}" ; pwd)"
-else
-  GIT_REPO="${GIT_REPO}/.git"
-fi
+#if [ -f "${GIT_REPO}/.git" ]; then
+#  SUBMODULE_REPO=$(cat "${GIT_REPO}/.git" | grep 'gitdir' | awk '{print $2}')
+#  GIT_REPO="$(cd "${GIT_REPO}" ; cd "${SUBMODULE_REPO}" ; pwd)"
+#else
+#  GIT_REPO="${GIT_REPO}/.git"
+#fi
 
 GIT_REPO=$(cd "${GIT_REPO}" ; pwd)
 
 # Make sure the repo specified is valid, submodule or normal
-if [[ -n "${SUBMODULE_REPO}" && ! -d "${GIT_REPO}" ]]; then
-  echo "Error: Submodule not a valid repository" >&2
-  exit -3
-elif [[ -z "${SUBMODULE_REPO}" && ! -d "${GIT_REPO}" ]]; then
-  echo "Error: Not a valid repository" >&2
-  exit -3
-fi
+#if [[ -n "${SUBMODULE_REPO}" && ! -d "${GIT_REPO}" ]]; then
+#  echo "Error: Submodule not a valid repository" >&2
+#  exit -3
+#elif [[ -z "${SUBMODULE_REPO}" && ! -d "${GIT_REPO}" ]]; then
+#  echo "Error: Not a valid repository" >&2
+#  exit -3
+#fi
 
 # Cleanup the hooks directory so it works properly
 HOOKS_DIR=$(dirname "${0}")
